config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
   if @book.save
    redirect_to book_path(@book.id), notice: 'Book was successfully created.' 
   else
     @books = Book.all
    render :index
   end
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
   else
    @books = Book.all
    render :edit
   end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books', notice: 'Book was successfully destroyed.'
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, local: true do |form| %>
 <% if @book.errors.any? %>
 <div id = "error_explanation">
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
   <ul>
    <% @book.errors.full_messages.each do |message| %>
    <il><%= message %></il>
    <% end %>
   </ul>
 </div>
 <% end %>
<% end %>

<%= form_with model: @book do |f| %>
<div class = "field">
 <label for = "book_title">Title</label>
  <%= f.text_field :title %>
</div>
<div class = "field">
 <label for = "book_title">Body</label>
  <%= f.text_area :body %>
</div>
 <%= f.submit 'Update Book' %>
 <% end %>

<div class = "link">
 <%= link_to "Show", book_path(@book.id) %>
 <%= "  |  " %>
 <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class = "message">
 <p id = "notice">
  <%= notice %>
 </p>
</div>

<header>
 <h1>Books</h1>
</header>

<body>
 <table>
  <thead>
   <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
   </tr>
  </thead>
 <tbody>
  <% @books.each do |book| %>
  <tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to "Show", book_path(book.id) %></td>
   <td><%= link_to "Edit", edit_book_path(book.id) %></td>
   <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
   <% end %>
  </tbody>
 </table>

<h2>New book</h2>

<% if @book.errors.any? %>
<div id = "error_explanation">
 <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
   <il><%= message %></il>
   <% end %>
 </ul>
</div>
<% end %>

<%= form_with model: @book, url:'/books', method: :post do |f| %>
 <div class = "field" >
   <label for = "book_title">Title</label>
    <%= f.text_field :title %>
 </div>
 <div class = "field" >
  <label for = "book_title">Body</label>
   <%= f.text_area :body %>
 </div>
  <%= f.submit 'Create Book' %>
 <% end %>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class = "message">
 <p id ="notice">
  <%= notice %>
 </p>
</div>

<p><span>Title: </span><%= @book.title %></p>
<p><span>Body: </span><%= @book.body %></p>

<div class ="link">
 <%= link_to "Edit", edit_book_path(@book.id) %>
 <%= "  |  " %>
 <%= link_to "Back", books_path %>
</div>

app/views/homes/top.html.erb
<header>
 <h1>ようこそ Bookers へ！</h1>
</header>

<body>
 <p><span>Bookers</span> では、さまざまな書籍に関するあなたの意見や</p>

 <p>印象を共有し交換することができます</p>

 <p><%= link_to "start", '/books' %></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>